services:
  app:
    build: .
    container_name: hoaxhunters_app
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - mongo
      - redis
    networks:
      - hoaxhunters_network

  mongo:
    image: mongo:6
    container_name: hoaxhunters_mongo
    restart: always
    ports:
      - "27017:27017"
    networks:
      - hoaxhunters_network
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:latest
    container_name: hoaxhunters_redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - hoaxhunters_network

networks:
  hoaxhunters_network:

volumes:
  mongo_data:
