name: Deploy to VPS

on:
  push:
    branches:
      - production # Jalankan action saat push ke branch `production`

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout kode terbaru
        uses: actions/checkout@v3

      - name: Setup SSH Key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem

      - name: first deploy to VPS
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key.pem ${{ secrets.VPS_IP }} << 'EOF'
            set -e  # Hentikan eksekusi jika ada error

            git clone https://github.com/rizaldiabyannata/hoaxhunter-backend.git

            # Bangun ulang image dan jalankan kembali layanan
            docker-compose up --build -d

            # Cek status container setelah restart
            docker ps -a
          EOF

      - name: Cleanup SSH Key
        run: rm -f private_key.pem
